### ISSUE TITLE
Even ver 3.1 does not work properly (or at all)

### ISSUE THREAD

**Issue by DM-LTR** [slinGitHub/Checkmate#1]
Hi there,

FYI: I am trying to run Checkmate from ver 1, but anytime I make a new install, app keeps on crashing, reloading constantly with "no data" message... regardless of NS token is/is not provided or how different roles are set (readable).
Galaxy M51. Android 11

**Comment by slinGitHub** [comment]
Hi, did you try the test download from the FAQ?

**Comment by slinGitHub** [comment]
No reply. Closed as of April 2022.
