### ISSUE TITLE
Grey bars

### ISSUE THREAD

**Issue by DagazArcane** [slinGitHub/Checkmate#2]
Apologies if not the right place.

Was wondering why some of my bars are grey?
Not red yellow or green even though they within ranges.

**Comment by slinGitHub** [comment]
Hi, if there is not enough data at this the bar will be grey. (To avoid the impression of a good day with only for example one data point in range)
Regards

**Comment by DagazArcane** [comment]
Thank you. It is connected to nightscout which is connected to a cgm so not 
sure what's going on? It has about 200 readings a day. Does it o ly pull 
down when open a d the. Only certain info?

**Comment by slinGitHub** [comment]
Hi, the colour is grey if there are less than 50% data points of your maximum data points at another day.

See the bar chart java file at line 104:

 
 ​            ​if​ ((hba1c_data​.​get(count ​-​ i)​.​nValues ​>​ (​0.5​ ​*​ maxValues)) ​||​ i ​==​ count) {

**Comment by slinGitHub** [comment]
Can you send me a screenshot?

**Comment by DagazArcane** [comment]
They were red green etc during the day then went grey the following day.

Great app BTW.

**Comment by DagazArcane** [comment]
Just thought you might want the days selected.

As you can see full chart.

Thanks

**Comment by slinGitHub** [comment]
Closed as of April 2022.
