### ISSUE TITLE
Support HbA1c - mmols/mol 

### ISSUE THREAD

**Issue by Andries-Smit** [slinGitHub/Checkmate#5]
For MMOL users would like to see HbA1c mmols/mol of the percentage
Conversion formulas :
 - Old = 0,0915 New + 2,15%
 - New = 10,93 Old – 23,5 mmol/mol

https://freestylediabetes.co.uk/what-is-diabetes/what-makes-glucose-levels-rise-and-fall/HbA1c
https://diabetessociety.com.au/documents/HbA1cConversionTable.pdf

**Comment by slinGitHub** [comment]
Thx for the input. Added it to the next update list.
